CREATE TYPE [dbo].[NotifySentType] AS TABLE (
    [NotiId]           BIGINT           NOT NULL,
    [userId]           NVARCHAR (MAX)   NULL,
    [custId]           NVARCHAR (MAX)   NULL,
    [email]            NVARCHAR (MAX)   NULL,
    [phone]            NVARCHAR (MAX)   NULL,
    [fullName]         NVARCHAR (MAX)   NULL,
    [room]             NVARCHAR (MAX)   NULL,
    [push_st]          INT              NULL,
    [sms_st]           INT              NULL,
    [read_st]          BIT              NULL,
    [email_st]         INT              NULL,
    [createId]         NVARCHAR (MAX)   NULL,
    [n_id]             UNIQUEIDENTIFIER NULL,
    [toId]             UNIQUEIDENTIFIER NULL,
    [Schedule]         DATETIME2 (7)    NULL,
    [subject]          NVARCHAR (MAX)   NULL,
    [content_notify]   NVARCHAR (MAX)   NULL,
    [content_sms]      NVARCHAR (MAX)   NULL,
    [content_email]    NVARCHAR (MAX)   NULL,
    [push_st_message]  NVARCHAR (MAX)   NULL,
    [sms_st_message]   NVARCHAR (MAX)   NULL,
    [email_st_message] NVARCHAR (MAX)   NULL,
    [external_param]   NVARCHAR (MAX)   NULL);

