CREATE TABLE [dbo].[CRM_Apartment_HandOver_Detail] (
    [HandOverDetailId]     BIGINT           IDENTITY (1, 1) NOT NULL,
    [HandOverId]           BIGINT           NULL,
    [ContractId]           BIGINT           NULL,
    [RoomCd]               NVARCHAR (50)    NOT NULL,
    [RoomCode]             NVARCHAR (50)    NOT NULL,
    [CustomerName]         NVARCHAR (100)   NOT NULL,
    [PhoneNumber]          NVARCHAR (20)    NULL,
    [TotalAmt]             DECIMAL (18, 2)  NULL,
    [TotalPayment]         DECIMAL (18, 2)  NULL,
    [BuildingCd]           NVARCHAR (50)    NOT NULL,
    [ProjectCd]            NVARCHAR (50)    NOT NULL,
    [HandOverExpectedDate] DATETIME         NULL,
    [RequestDateCus]       DATETIME         NULL,
    [IsPMCheck]            BIT              NULL,
    [IsKTCheck]            BIT              NULL,
    [IsBNTCheck]           BIT              NULL,
    [IsAgreeReceive]       BIT              NULL,
    [IsComplete]           BIT              NULL,
    [HandOverDtStatus]     INT              NULL,
    [PercentDone]          INT              NULL,
    [Created]              DATETIME         CONSTRAINT [DF_CRM_Apartment_HandOver_Detail_Created] DEFAULT ((0)) NULL,
    [CreatedBy]            NVARCHAR (50)    NULL,
    [Modified]             DATETIME         NULL,
    [ModifiedBy]           NVARCHAR (50)    NULL,
    [oid]                  UNIQUEIDENTIFIER CONSTRAINT [DF_CRM_Apartment_HandOver_Detail_oid] DEFAULT (newid()) NOT NULL,
    [tenant_oid]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_CRM_Apartment_HandOver] PRIMARY KEY CLUSTERED ([HandOverDetailId] ASC),
    CONSTRAINT [FK_CRM_Apartment_HandOver_Detail_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

