CREATE TABLE [dbo].[maintenance_plan] (
    [oid]                  UNIQUEIDENTIFIER NOT NULL,
    [site_id]              UNIQUEIDENTIFIER NOT NULL,
    [plan_code]            NVARCHAR (50)    NOT NULL,
    [plan_name]            NVARCHAR (200)   NOT NULL,
    [description]          NVARCHAR (MAX)   NULL,
    [maintenance_type]     NVARCHAR (50)    NOT NULL,
    [priority]             INT              NOT NULL,
    [frequency]            NVARCHAR (50)    NOT NULL,
    [start_date]           DATE             NOT NULL,
    [end_date]             DATE             NULL,
    [execution_start_time] TIME (7)         NULL,
    [execution_end_time]   TIME (7)         NULL,
    [auto_notification]    BIT              DEFAULT ((0)) NOT NULL,
    [area_cd]              NVARCHAR (50)    NULL,
    [building_cds]         NVARCHAR (MAX)   NULL,
    [asset_oids]           NVARCHAR (MAX)   NULL,
    [assignment_type]      NVARCHAR (50)    NOT NULL,
    [assignee_oid]         UNIQUEIDENTIFIER NULL,
    [team_oid]             UNIQUEIDENTIFIER NULL,
    [external_unit]        NVARCHAR (200)   NULL,
    [supervisor_oid]       UNIQUEIDENTIFIER NULL,
    [estimated_hours]      DECIMAL (18, 2)  NULL,
    [status]               INT              DEFAULT ((0)) NOT NULL,
    [create_at]            DATETIME         DEFAULT (getdate()) NOT NULL,
    [create_by]            NVARCHAR (100)   NULL,
    [modify_at]            DATETIME         NULL,
    [modify_by]            NVARCHAR (100)   NULL,
    [is_delete]            BIT              DEFAULT ((0)) NOT NULL,
    [tenant_oid]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_maintenance_plan] PRIMARY KEY CLUSTERED ([oid] ASC),
    CONSTRAINT [FK_maintenance_plan_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

