CREATE TABLE [dbo].[MAS_Card_H] (
    [CardId]        INT              NOT NULL,
    [CardCd]        NVARCHAR (50)    NOT NULL,
    [CardTypeId]    INT              NULL,
    [ImageUrl]      NVARCHAR (250)   NULL,
    [IssueDate]     DATETIME         NULL,
    [ExpireDate]    DATETIME         NULL,
    [CustId]        NVARCHAR (50)    NULL,
    [Card_St]       INT              NULL,
    [IsVip]         BIT              NULL,
    [CardName]      NVARCHAR (150)   NULL,
    [IsDaily]       BIT              NOT NULL,
    [IsClose]       BIT              NULL,
    [CloseDate]     DATETIME         NULL,
    [RequestId]     INT              NULL,
    [ApartmentId]   INT              NULL,
    [ProjectCd]     NVARCHAR (30)    NULL,
    [VehicleTypeId] INT              NULL,
    [StarLevel]     INT              NULL,
    [IsGuest]       BIT              NULL,
    [SaveDate]      DATETIME         NULL,
    [SaveId]        NVARCHAR (50)    NULL,
    [isVehicle]     BIT              NULL,
    [isCredit]      BIT              NULL,
    [partner_id]    INT              NULL,
    [created_by]    NVARCHAR (100)   NULL,
    [CloseBy]       NVARCHAR (100)   NULL,
    [Reason]        NVARCHAR (450)   DEFAULT (NULL) NULL,
    [IsHardLock]    BIT              NULL,
    [oid]           UNIQUEIDENTIFIER CONSTRAINT [DF_MAS_Card_H_oid] DEFAULT (newid()) NOT NULL,
    [tenant_oid]    UNIQUEIDENTIFIER NULL,
    [apartOid]      UNIQUEIDENTIFIER NULL,
    [cardOid]       UNIQUEIDENTIFIER NULL,
    CONSTRAINT [FK_MAS_Card_H_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

