CREATE TABLE [dbo].[MAS_CardVehicle_H] (
    [CardVehicleId]    INT              NOT NULL,
    [AssignDate]       DATETIME         NULL,
    [CardId]           INT              NOT NULL,
    [CustId]           NVARCHAR (50)    NOT NULL,
    [VehicleNo]        NVARCHAR (16)    NOT NULL,
    [VehicleTypeId]    INT              NULL,
    [VehicleName]      NVARCHAR (100)   NULL,
    [VehicleColor]     NVARCHAR (100)   NULL,
    [StartTime]        DATETIME         NULL,
    [EndTime]          DATETIME         NULL,
    [Status]           INT              NULL,
    [ServiceId]        INT              NULL,
    [RegCardVehicleId] INT              NULL,
    [RequestId]        INT              NULL,
    [isVehicleNone]    BIT              NULL,
    [monthlyType]      INT              NULL,
    [VehicleNum]       INT              NULL,
    [lastReceivable]   DATETIME         NULL,
    [Mkr_Id]           NVARCHAR (50)    NULL,
    [Mkr_Dt]           DATETIME         NULL,
    [Auth_id]          NVARCHAR (200)   NULL,
    [Auth_Dt]          DATETIME         NULL,
    [ProjectCd]        NVARCHAR (30)    NULL,
    [ApartmentId]      BIGINT           NULL,
    [Reason]           NVARCHAR (200)   NULL,
    [SaveDate]         DATETIME         NULL,
    [SaveId]           NVARCHAR (50)    NULL,
    [endTime_Tmp]      DATETIME         NULL,
    [isCharginFee]     BIT              NULL,
    [SaveKey]          NVARCHAR (100)   NULL,
    [ProcName]         NVARCHAR (100)   NULL,
    [isHardLock]       BIT              NULL,
    [ImageUrl]         NVARCHAR (MAX)   NULL,
    [oid]              UNIQUEIDENTIFIER CONSTRAINT [DF_MAS_CardVehicle_H_oid] DEFAULT (newid()) NOT NULL,
    [tenant_oid]       UNIQUEIDENTIFIER NULL,
    [apartOid]         UNIQUEIDENTIFIER NULL,
    [cardOid]          UNIQUEIDENTIFIER NULL,
    CONSTRAINT [FK_MAS_CardVehicle_H_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

