CREATE TABLE [dbo].[MAS_Customers_Save] (
    [CustId]      NVARCHAR (50)    NOT NULL,
    [Cif_No]      NVARCHAR (50)    NULL,
    [FullName]    NVARCHAR (250)   NULL,
    [FirstName]   NVARCHAR (100)   NULL,
    [LastName]    NVARCHAR (150)   NULL,
    [AvatarUrl]   NVARCHAR (250)   NULL,
    [IsSex]       BIT              NULL,
    [Birthday]    DATETIME         NULL,
    [RelationId]  INT              NULL,
    [Phone]       NVARCHAR (50)    NULL,
    [Phone2]      NVARCHAR (30)    NULL,
    [Email]       NVARCHAR (150)   NULL,
    [Email2]      NVARCHAR (150)   NULL,
    [Pass_No]     NVARCHAR (50)    NULL,
    [Pass_Dt]     DATE             NULL,
    [Pass_Plc]    NVARCHAR (150)   NULL,
    [Address]     NVARCHAR (350)   NULL,
    [ProvinceCd]  NVARCHAR (30)    NULL,
    [IsForeign]   BIT              NULL,
    [CountryCd]   NVARCHAR (30)    NULL,
    [IsContact]   BIT              NULL,
    [IsEmployee]  BIT              NULL,
    [sysDate]     DATETIME         NULL,
    [IsAdmin]     BIT              NULL,
    [ApartmentId] INT              NULL,
    [IsHost]      BIT              NULL,
    [Auth_St]     BIT              NULL,
    [Auth_Dt]     DATETIME         NULL,
    [Auth_Id]     NVARCHAR (50)    NULL,
    [saveDate]    DATETIME         NULL,
    [saveId]      NVARCHAR (50)    NULL,
    [oid]         UNIQUEIDENTIFIER CONSTRAINT [DF_MAS_Customers_Save_oid] DEFAULT (newid()) NOT NULL,
    [tenant_oid]  UNIQUEIDENTIFIER NULL,
    CONSTRAINT [FK_MAS_Customers_Save_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

