CREATE TABLE [dbo].[MAS_Service_Receipts_H] (
    [ReceiptId]          INT              IDENTITY (1, 1) NOT NULL,
    [ReceiptNo]          NVARCHAR (20)    NULL,
    [ReceiptDt]          DATETIME         NULL,
    [CustId]             NVARCHAR (50)    NULL,
    [ApartmentId]        BIGINT           NULL,
    [ReceiveId]          BIGINT           NULL,
    [TranferCd]          NVARCHAR (200)   NULL,
    [Object]             NVARCHAR (200)   NULL,
    [Pass_No]            NVARCHAR (50)    NULL,
    [Pass_dt]            DATETIME         NULL,
    [Pass_Plc]           NVARCHAR (50)    NULL,
    [Address]            NVARCHAR (200)   NULL,
    [Contents]           NVARCHAR (300)   NULL,
    [Attach]             NVARCHAR (30)    NULL,
    [IsDBCR]             BIT              NULL,
    [Amount]             FLOAT (53)       NOT NULL,
    [CreatorCd]          NVARCHAR (50)    NULL,
    [CreateDate]         DATETIME         NULL,
    [AccountLeft]        NVARCHAR (20)    NULL,
    [AccountRight]       NVARCHAR (20)    NULL,
    [ProjectCd]          NVARCHAR (30)    NULL,
    [ReceiptBillUrl]     NVARCHAR (350)   NULL,
    [ReceiptBillViewUrl] NVARCHAR (350)   NULL,
    [AmtSubtractPoint]   DECIMAL (18)     NULL,
    [Ref_No]             NVARCHAR (50)    NULL,
    [RefundAmt]          DECIMAL (18)     NULL,
    [SaveKey]            NVARCHAR (200)   NULL,
    [SaveId]             NVARCHAR (50)    NULL,
    [SaveDate]           DATETIME         NULL,
    [ProcName]           NVARCHAR (200)   NULL,
    [oid]                UNIQUEIDENTIFIER CONSTRAINT [DF_MAS_Service_Receipts_H_oid] DEFAULT (newid()) NOT NULL,
    [tenant_oid]         UNIQUEIDENTIFIER NULL,
    [apartOid]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [FK_MAS_Service_Receipts_H_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

