CREATE TABLE [dbo].[NotifyTemplate] (
    [tempId]           UNIQUEIDENTIFIER CONSTRAINT [DF_NotifyTemplate_tempId] DEFAULT (newid()) NOT NULL,
    [tempName]         NVARCHAR (200)   NOT NULL,
    [templateTypeId]   INT              NULL,
    [notiDt]           DATETIME         NULL,
    [notiType]         INT              NULL,
    [subject]          NVARCHAR (500)   NULL,
    [actionlist]       NVARCHAR (150)   NULL,
    [content_notify]   NVARCHAR (300)   NULL,
    [content_sms]      NVARCHAR (1000)  NULL,
    [content_type]     INT              NULL,
    [content_markdown] NVARCHAR (MAX)   NULL,
    [content_email]    NVARCHAR (MAX)   NULL,
    [bodytype]         NVARCHAR (10)    NULL,
    [external_key]     NVARCHAR (50)    NULL,
    [external_sub]     NVARCHAR (30)    NULL,
    [external_param]   NVARCHAR (MAX)   NULL,
    [external_event]   NVARCHAR (50)    NULL,
    [source_key]       NVARCHAR (50)    NULL,
    [source_ref]       UNIQUEIDENTIFIER NULL,
    [createId]         NVARCHAR (100)   NULL,
    [createDt]         DATETIME         CONSTRAINT [DF_NotifyTemplate_SysDate] DEFAULT (getdate()) NULL,
    [send_by]          NVARCHAR (200)   NULL,
    [send_name]        NVARCHAR (50)    NULL,
    [brand_name]       NVARCHAR (20)    NULL,
    [bcc]              NVARCHAR (MAX)   NULL,
    [n_id]             UNIQUEIDENTIFIER NULL,
    [app_st]           INT              NULL,
    [tempCd]           NVARCHAR (100)   NULL,
    [notiAvatarUrl]    NVARCHAR (500)   NULL,
    [projectCd]        NVARCHAR (10)    NULL,
    [parentId]         UNIQUEIDENTIFIER NULL,
    [formulaId]        UNIQUEIDENTIFIER NULL,
    [tenant_oid]       UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_NotifyTemplate] PRIMARY KEY CLUSTERED ([tempId] ASC),
    CONSTRAINT [FK_NotifyTemplate_tenant_oid] FOREIGN KEY ([tenant_oid]) REFERENCES [dbo].[MAS_Projects] ([oid])
);

